apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec: 
  project: default
  source: 
    repoURL: https://github.com/pavlovskyantony/argocd-tutorial.git
    targetRevision: HEAD
    path: environment/dev/my-app-2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: 
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true